# Generated by Django 2.0.4 on 2018-04-17 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contacts',
            name='created',
        ),
        migrations.RemoveField(
            model_name='contacts',
            name='updated',
        ),
        migrations.AlterField(
            model_name='contacts',
            name='job_title',
            field=models.CharField(default='x', max_length=40),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='notes',
            field=models.TextField(blank=True, default='none', null=True),
        ),
    ]
