# Generated by Django 2.0.4 on 2018-04-17 03:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_auto_20180416_2117'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contacts',
            name='job_title',
        ),
        migrations.RemoveField(
            model_name='contacts',
            name='notes',
        ),
    ]
